version: '3.8'

services:
 mysql:
  platform: linux/x86_64
  build: ./docker/mysql
  container_name: apollo-mysql
  ports:
    - '33065:3306'
  environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 'caadvance'
      MYSQL_DATABASE: 'apollo_mysql'
      MYSQL_USER: 'apollo_mysql'
      MYSQL_PASSWORD: 'apollo_mysql'
  volumes:
      - mysql-volume:/var/lib/mysql
    #   - ./docker/mysql/my.config:/etc/my.cnf
    #   - ./docker/mysql/init:/docker-entrypoint-initdb.d
  command: 
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      - --default-storage-engine=innodb
      - --sql-mode=NO_ENGINE_SUBSTITUTION

volumes:
  mysql-volume:
   name: apollo-mysql
   driver: local